server:
  port: 8003

spring:
  application:
    name: service-vod
  profiles:
    active: dev
  servlet:
    multipart:
      #最大上传单个文件大小，默认1M
      max-file-size: 1024MB
      # 最大置总上传的数据大小 ：默认10M
      max-request-size: 1024MB
  #cloud
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#阿里云
aliyun:
  vod:
    file:
      keyid: LTAI5tPJWu5GMxLQtjm3Yqyf
      keysecret: IEVkO9PG68juvqUHUhI3nURSmM6X8i

